// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQt91YofxFCMtPai3AZPssv7tSu2e06j8',
    appId: '1:199863734141:web:f809db46cf7d9fba730614',
    messagingSenderId: '199863734141',
    projectId: 'flutter-login-app-8c1e9',
    authDomain: 'flutter-login-app-8c1e9.firebaseapp.com',
    storageBucket: 'flutter-login-app-8c1e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzIWTlCjVkbDv0hJ5CcIiOQZvp4P9MXJE',
    appId: '1:199863734141:android:b5abcc8208eaf5f3730614',
    messagingSenderId: '199863734141',
    projectId: 'flutter-login-app-8c1e9',
    storageBucket: 'flutter-login-app-8c1e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5DJ0Sw9Vq3W1np_QFJpfpoJHuJJs4dDk',
    appId: '1:199863734141:ios:7e415f97bd04f306730614',
    messagingSenderId: '199863734141',
    projectId: 'flutter-login-app-8c1e9',
    storageBucket: 'flutter-login-app-8c1e9.appspot.com',
    iosClientId: '199863734141-n5hejqrj02mvv5hbgss5o90sn5psojq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5DJ0Sw9Vq3W1np_QFJpfpoJHuJJs4dDk',
    appId: '1:199863734141:ios:7e415f97bd04f306730614',
    messagingSenderId: '199863734141',
    projectId: 'flutter-login-app-8c1e9',
    storageBucket: 'flutter-login-app-8c1e9.appspot.com',
    iosClientId: '199863734141-n5hejqrj02mvv5hbgss5o90sn5psojq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
